# Travis CI config for Debspawn

language: python
dist: trusty

addons:
  apt:
    packages:
    - xsltproc
    - docbook-xsl

python:
  - "3.5"
  - "3.6"
  - "nightly"

matrix:
  allow_failures:
    - python: "nightly"

install:
 - pip install flake8

script:
  - ./setup.py build
  - ./setup.py install --root=/tmp
  - flake8 --ignore E501 ./
