# Travis CI config for Debspawn

language: python
dist: bionic

addons:
  apt:
    update: true
    packages:
    - xsltproc
    - docbook-xsl
    - docbook-xml
    - zstd
    - systemd-container
    - debootstrap

python:
  - "3.7"
  - "3.8"
  - "nightly"

matrix:
  allow_failures:
    - python: "nightly"

install:
 - pip install flake8

script:
  - ./setup.py build
  - ./setup.py install --root=/tmp
  - rm -rf build/
  - flake8 ./
