name: Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9' ]

    name: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Update cache
      run: sudo apt-get update -qq

    - name: Install system prerequisites
      run: sudo apt-get install -yq
             xsltproc
             docbook-xsl
             docbook-xml
             zstd
             systemd
             systemd-container
             debootstrap

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install toml pkgconfig flake8 pytest pylint mypy

    - name: Build & Install
      run: |
        ./setup.py build
        ./setup.py install --single-version-externally-managed --root=/tmp
        rm -rf build/

    - name: Test
      run: |
        sudo $(which python3) -m pytest
        rm -rf build/

    - name: Lint (flake8)
      run: |
        python -m flake8 ./ --statistics
        python -m flake8 debspawn/dsrun --statistics

    - name: Lint (pylint)
      run: |
        python -m pylint -f colorized ./debspawn
        python -m pylint -f colorized ./debspawn/dsrun
        python -m pylint -f colorized ./tests ./data
        python -m pylint -f colorized setup.py

    - name: Lint (mypy)
      run: |
        python -m mypy .
        python -m mypy ./debspawn/dsrun
